// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monchotradebackend.data;

#nullable disable

namespace monchotradeBackend.Data.Migrations.Sqlite
{
    [DbContext(typeof(MonchoDbContext))]
    [Migration("20241114185036_AddExchangeSeeds")]
    partial class AddExchangeSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("monchotradebackend.models.entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home Decor"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitiatorProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiverProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InitiatorProductId");

                    b.HasIndex("ReceiverProductId");

                    b.HasIndex("Status");

                    b.HasIndex("InitiatorUserId", "Status");

                    b.HasIndex("ReceiverUserId", "Status");

                    b.ToTable("Exchanges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(723),
                            InitiatorProductId = 1,
                            InitiatorUserId = 1,
                            Notes = "Jeans for headphones",
                            ReceiverProductId = 3,
                            ReceiverUserId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(727),
                            InitiatorProductId = 2,
                            InitiatorUserId = 1,
                            Notes = "T-Shirt for sneakers",
                            ReceiverProductId = 5,
                            ReceiverUserId = 3,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(731),
                            InitiatorProductId = 3,
                            InitiatorUserId = 2,
                            Notes = "Headphones for charger",
                            ReceiverProductId = 7,
                            ReceiverUserId = 4,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(734),
                            InitiatorProductId = 4,
                            InitiatorUserId = 2,
                            Notes = "Speaker for shirt",
                            ReceiverProductId = 9,
                            ReceiverUserId = 5,
                            RejectionReason = "Item condition not as expected",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(737),
                            InitiatorProductId = 5,
                            InitiatorUserId = 3,
                            Notes = "Sneakers for laptop stand",
                            ReceiverProductId = 11,
                            ReceiverUserId = 6,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(740),
                            InitiatorProductId = 6,
                            InitiatorUserId = 3,
                            Notes = "Running shoes for watch",
                            ReceiverProductId = 13,
                            ReceiverUserId = 7,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(743),
                            InitiatorProductId = 7,
                            InitiatorUserId = 4,
                            Notes = "Charger for jacket",
                            ReceiverProductId = 15,
                            ReceiverUserId = 8,
                            RejectionReason = "Found another exchange",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(747),
                            InitiatorProductId = 8,
                            InitiatorUserId = 4,
                            Notes = "Power bank for tablet",
                            ReceiverProductId = 17,
                            ReceiverUserId = 9,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(750),
                            InitiatorProductId = 9,
                            InitiatorUserId = 5,
                            Notes = "Formal shirt for yoga mat",
                            ReceiverProductId = 19,
                            ReceiverUserId = 10,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(753),
                            InitiatorProductId = 10,
                            InitiatorUserId = 5,
                            Notes = "Dress pants for desk organizer",
                            ReceiverProductId = 21,
                            ReceiverUserId = 11,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(757),
                            InitiatorProductId = 11,
                            InitiatorUserId = 6,
                            Notes = "Laptop stand for vase",
                            ReceiverProductId = 23,
                            ReceiverUserId = 12,
                            RejectionReason = "Size doesn't match description",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(760),
                            InitiatorProductId = 12,
                            InitiatorUserId = 6,
                            Notes = "Mouse for gaming mouse",
                            ReceiverProductId = 25,
                            ReceiverUserId = 13,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(763),
                            InitiatorProductId = 13,
                            InitiatorUserId = 7,
                            Notes = "Digital watch for wall art",
                            ReceiverProductId = 27,
                            ReceiverUserId = 14,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(767),
                            InitiatorProductId = 14,
                            InitiatorUserId = 7,
                            Notes = "Fitness tracker for thermostat",
                            ReceiverProductId = 29,
                            ReceiverUserId = 15,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(770),
                            InitiatorProductId = 15,
                            InitiatorUserId = 8,
                            Notes = "Jacket for sunglasses",
                            ReceiverProductId = 31,
                            ReceiverUserId = 16,
                            RejectionReason = "Item no longer available",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(773),
                            InitiatorProductId = 16,
                            InitiatorUserId = 8,
                            Notes = "Scarf for hoodie",
                            ReceiverProductId = 33,
                            ReceiverUserId = 17,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(776),
                            InitiatorProductId = 17,
                            InitiatorUserId = 9,
                            Notes = "Tablet for portable charger",
                            ReceiverProductId = 35,
                            ReceiverUserId = 18,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(779),
                            InitiatorProductId = 18,
                            InitiatorUserId = 9,
                            Notes = "Tablet case for cookware",
                            ReceiverProductId = 37,
                            ReceiverUserId = 19,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(782),
                            InitiatorProductId = 19,
                            InitiatorUserId = 10,
                            Notes = "Yoga mat for pants",
                            ReceiverProductId = 39,
                            ReceiverUserId = 20,
                            RejectionReason = "Changed my mind",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(785),
                            InitiatorProductId = 20,
                            InitiatorUserId = 10,
                            Notes = "Dumbbells for jeans",
                            ReceiverProductId = 1,
                            ReceiverUserId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(788),
                            InitiatorProductId = 21,
                            InitiatorUserId = 11,
                            Notes = "Desk organizer for headphones",
                            ReceiverProductId = 3,
                            ReceiverUserId = 2,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(792),
                            InitiatorProductId = 22,
                            InitiatorUserId = 11,
                            Notes = "Notepad for sneakers",
                            ReceiverProductId = 5,
                            ReceiverUserId = 3,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(795),
                            InitiatorProductId = 23,
                            InitiatorUserId = 12,
                            Notes = "Vase for charger",
                            ReceiverProductId = 7,
                            ReceiverUserId = 4,
                            RejectionReason = "Distance too far for exchange",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(798),
                            InitiatorProductId = 24,
                            InitiatorUserId = 12,
                            Notes = "Pillow for shirt",
                            ReceiverProductId = 9,
                            ReceiverUserId = 5,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(801),
                            InitiatorProductId = 25,
                            InitiatorUserId = 13,
                            Notes = "Gaming mouse for laptop stand",
                            ReceiverProductId = 11,
                            ReceiverUserId = 6,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(804),
                            InitiatorProductId = 26,
                            InitiatorUserId = 13,
                            Notes = "Keyboard for watch",
                            ReceiverProductId = 13,
                            ReceiverUserId = 7,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(808),
                            InitiatorProductId = 27,
                            InitiatorUserId = 14,
                            Notes = "Wall art for jacket",
                            ReceiverProductId = 15,
                            ReceiverUserId = 8,
                            RejectionReason = "Item value mismatch",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(888),
                            InitiatorProductId = 28,
                            InitiatorUserId = 14,
                            Notes = "Lamp for tablet",
                            ReceiverProductId = 17,
                            ReceiverUserId = 9,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(892),
                            InitiatorProductId = 29,
                            InitiatorUserId = 15,
                            Notes = "Thermostat for yoga mat",
                            ReceiverProductId = 19,
                            ReceiverUserId = 10,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(895),
                            InitiatorProductId = 30,
                            InitiatorUserId = 15,
                            Notes = "Air purifier for organizer",
                            ReceiverProductId = 21,
                            ReceiverUserId = 11,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(898),
                            InitiatorProductId = 31,
                            InitiatorUserId = 16,
                            Notes = "Sunglasses for vase",
                            ReceiverProductId = 23,
                            ReceiverUserId = 12,
                            RejectionReason = "Communication issues",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(901),
                            InitiatorProductId = 32,
                            InitiatorUserId = 16,
                            Notes = "Wallet for gaming mouse",
                            ReceiverProductId = 25,
                            ReceiverUserId = 13,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(904),
                            InitiatorProductId = 33,
                            InitiatorUserId = 17,
                            Notes = "Hoodie for wall art",
                            ReceiverProductId = 27,
                            ReceiverUserId = 14,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(907),
                            InitiatorProductId = 34,
                            InitiatorUserId = 17,
                            Notes = "Cap for thermostat",
                            ReceiverProductId = 29,
                            ReceiverUserId = 15,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(911),
                            InitiatorProductId = 35,
                            InitiatorUserId = 18,
                            Notes = "Portable charger for sunglasses",
                            ReceiverProductId = 31,
                            ReceiverUserId = 16,
                            RejectionReason = "Schedule conflicts for meetup",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(914),
                            InitiatorProductId = 36,
                            InitiatorUserId = 18,
                            Notes = "USB cables for hoodie",
                            ReceiverProductId = 33,
                            ReceiverUserId = 17,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(917),
                            InitiatorProductId = 37,
                            InitiatorUserId = 19,
                            Notes = "Cookware for charger",
                            ReceiverProductId = 35,
                            ReceiverUserId = 18,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(920),
                            InitiatorProductId = 38,
                            InitiatorUserId = 19,
                            Notes = "Knife set for jeans",
                            ReceiverProductId = 1,
                            ReceiverUserId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(923),
                            InitiatorProductId = 39,
                            InitiatorUserId = 20,
                            Notes = "Pants for headphones",
                            ReceiverProductId = 3,
                            ReceiverUserId = 2,
                            RejectionReason = "Product quality concerns",
                            Status = "Rejected"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(926),
                            InitiatorProductId = 40,
                            InitiatorUserId = 20,
                            Notes = "Sweater for sneakers",
                            ReceiverProductId = 5,
                            ReceiverUserId = 3,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(74),
                            Description = "Classic blue jeans for everyday wear",
                            IsActive = true,
                            Name = "Men's Jeans",
                            Quantity = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(79),
                            Description = "Comfortable cotton t-shirt, perfect for casual outings",
                            IsActive = true,
                            Name = "Casual T-Shirt",
                            Quantity = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(83),
                            Description = "Stylish white formal shirt, perfect for office",
                            IsActive = true,
                            Name = "Formal Shirt",
                            Quantity = 11,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(149),
                            Description = "Comfortable black dress pants for formal events",
                            IsActive = true,
                            Name = "Dress Pants",
                            Quantity = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(161),
                            Description = "Stylish and warm winter jacket",
                            IsActive = true,
                            Name = "Men's Jacket",
                            Quantity = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(167),
                            Description = "Soft wool scarf for cold weather",
                            IsActive = true,
                            Name = "Wool Scarf",
                            Quantity = 7,
                            UserId = 8
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(171),
                            Description = "Comfortable cotton hoodie",
                            IsActive = true,
                            Name = "Cotton Hoodie",
                            Quantity = 8,
                            UserId = 17
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(186),
                            Description = "Adjustable sports cap",
                            IsActive = true,
                            Name = "Sports Cap",
                            Quantity = 15,
                            UserId = 17
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(190),
                            Description = "Comfortable everyday pants",
                            IsActive = true,
                            Name = "Pants",
                            Quantity = 6,
                            UserId = 20
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(193),
                            Description = "Warm sweater for winter",
                            IsActive = true,
                            Name = "Sweater",
                            Quantity = 15,
                            UserId = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(196),
                            Description = "Fast-charging USB-C charger",
                            IsActive = true,
                            Name = "Smartphone Charger",
                            Quantity = 15,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(200),
                            Description = "10,000mAh power bank for mobile devices",
                            IsActive = true,
                            Name = "Power Bank",
                            Quantity = 9,
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(203),
                            Description = "Sporty digital watch with water resistance",
                            IsActive = true,
                            Name = "Digital Watch",
                            Quantity = 14,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(206),
                            Description = "Tracks steps, calories, and more",
                            IsActive = true,
                            Name = "Fitness Tracker",
                            Quantity = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(214),
                            Description = "Polarized sunglasses with UV protection",
                            IsActive = true,
                            Name = "Sunglasses",
                            Quantity = 10,
                            UserId = 16
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(245),
                            Description = "Classic leather wallet with multiple compartments",
                            IsActive = true,
                            Name = "Leather Wallet",
                            Quantity = 9,
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(250),
                            Description = "Noise-cancelling headphones with high-quality sound",
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Quantity = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(254),
                            Description = "Portable speaker with long battery life",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Quantity = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(257),
                            Description = "10-inch tablet with high-resolution display",
                            IsActive = true,
                            Name = "Tablet",
                            Quantity = 6,
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(260),
                            Description = "Protective case for 10-inch tablet",
                            IsActive = true,
                            Name = "Tablet Case",
                            Quantity = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(263),
                            Description = "High-precision gaming mouse",
                            IsActive = true,
                            Name = "Gaming Mouse",
                            Quantity = 6,
                            UserId = 13
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(266),
                            Description = "Tactile mechanical keyboard",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Quantity = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(269),
                            Description = "Programmable smart thermostat",
                            IsActive = true,
                            Name = "Smart Thermostat",
                            Quantity = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(272),
                            Description = "Compact air purifier for small rooms",
                            IsActive = true,
                            Name = "Air Purifier",
                            Quantity = 3,
                            UserId = 15
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(275),
                            Description = "Compact charger for mobile devices",
                            IsActive = true,
                            Name = "Portable Charger",
                            Quantity = 14,
                            UserId = 18
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(279),
                            Description = "Set of 3 USB cables",
                            IsActive = true,
                            Name = "USB Cable Set",
                            Quantity = 12,
                            UserId = 18
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(282),
                            Description = "Non-stick cookware set",
                            IsActive = true,
                            Name = "Cookware Set",
                            Quantity = 6,
                            UserId = 19
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(291),
                            Description = "Stainless steel knives for every need",
                            IsActive = true,
                            Name = "Knife Set",
                            Quantity = 7,
                            UserId = 19
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(294),
                            Description = "Elegant ceramic vase for home decor",
                            IsActive = true,
                            Name = "Ceramic Vase",
                            Quantity = 7,
                            UserId = 12
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(298),
                            Description = "Soft pillow with a decorative cover",
                            IsActive = true,
                            Name = "Decorative Pillow",
                            Quantity = 10,
                            UserId = 12
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(301),
                            Description = "Modern abstract wall art",
                            IsActive = true,
                            Name = "Wall Art",
                            Quantity = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(304),
                            Description = "Stylish table lamp with adjustable brightness",
                            IsActive = true,
                            Name = "Table Lamp",
                            Quantity = 8,
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(471),
                            Description = "Comfortable and durable sports shoes",
                            IsActive = true,
                            Name = "Sports Sneakers",
                            Quantity = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(476),
                            Description = "Lightweight running shoes for everyday exercise",
                            IsActive = true,
                            Name = "Running Shoes",
                            Quantity = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(479),
                            Description = "Ergonomic stand for laptops",
                            IsActive = true,
                            Name = "Laptop Stand",
                            Quantity = 8,
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(483),
                            Description = "Compact wireless mouse for convenience",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Quantity = 13,
                            UserId = 6
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(486),
                            Description = "Keeps your desk neat and organized",
                            IsActive = true,
                            Name = "Desk Organizer",
                            Quantity = 8,
                            UserId = 11
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(489),
                            Description = "Set of three notepads",
                            IsActive = true,
                            Name = "Notepad Set",
                            Quantity = 15,
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(493),
                            Description = "Non-slip yoga mat for workouts",
                            IsActive = true,
                            Name = "Yoga Mat",
                            Quantity = 12,
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 11, 14, 10, 50, 36, 523, DateTimeKind.Local).AddTicks(496),
                            Description = "Adjustable dumbbells for home workouts",
                            IsActive = true,
                            Name = "Dumbbells Set",
                            Quantity = 3,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Url = "2c2abcc8-d9de-4657-b2ea-9cb6317e35c1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            Url = "d8440f61-bf9a-45f8-b18c-e9b7e2d35ba8.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Url = "13268719-b95e-4ffa-af40-83b1c7a7a079.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 4,
                            Url = "6c97ef84-b64c-4f70-8995-71f8889dd311.png"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProfileImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "64d3f2dd-200a-49d4-b1ac-cb3541ba22f0.jpg",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Url = "bae63af5-6084-465d-b4dc-b6549dee41ee.jpg",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 5, 15),
                            Country = "Mexico",
                            Email = "ana.martinezgomez@example.com",
                            LastName = "Martinez",
                            Name = "Ana Luisa",
                            PasswordHash = "$2a$11$pWU8w/2CsgnLF4X0c4hRyeye22RBgelCiTXTJySi1G/v9Ii7G44i.",
                            PhoneNumber = "+52 55 1234 5678",
                            SecondLastName = "Gomez"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1985, 8, 22),
                            Country = "Mexico",
                            Email = "carlos.gomezlopez@example.com",
                            LastName = "Gomez",
                            Name = "Carlos",
                            PasswordHash = "$2a$11$5Wh38j0Wfs9FUAIBaSZreeoBe.t7mnPzPfsuoG6FaOE7yBCOljY6m",
                            PhoneNumber = "+52 33 9876 5432",
                            SecondLastName = "Lopez"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1992, 3, 10),
                            Country = "Mexico",
                            Email = "miguel.torresramirez@example.com",
                            LastName = "Torres",
                            Name = "Miguel",
                            PasswordHash = "$2a$11$Ap47oQ4bqlEMb7O/27rCSOnMvEy0j75KuP26kudEabfmCZLjBZJh6",
                            PhoneNumber = "+52 81 5555 4444",
                            SecondLastName = "Ramirez"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1988, 11, 5),
                            Country = "Mexico",
                            Email = "laura.rodriguezfernandez@example.com",
                            LastName = "Rodriguez",
                            Name = "Laura",
                            PasswordHash = "$2a$11$woLtTTaJ2jeald5cmc1QhufeIUdWAPhYgwwe5l7fgMUDYCprI7wSO",
                            PhoneNumber = "+52 55 2222 3333",
                            SecondLastName = "Fernandez"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1995, 7, 18),
                            Country = "Mexico",
                            Email = "juan.sanchezmartinez@example.com",
                            LastName = "Sanchez",
                            Name = "Juan Carlos",
                            PasswordHash = "$2a$11$Scuf1pNXCsl/5HHvWE6iy.qsLpXrx/VsMuJXaKjKwE3n7k4yylxk.",
                            PhoneNumber = "+52 33 7777 8888",
                            SecondLastName = "Martinez"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1987, 9, 30),
                            Country = "Mexico",
                            Email = "sofia.ramirezcastillo@example.com",
                            LastName = "Ramirez",
                            Name = "Sofia",
                            PasswordHash = "$2a$11$0aR39aKAo50JfN3gctofCOviIqwHxxfHpy5RYfdZhSTlkWnHSsKHy",
                            PhoneNumber = "+52 81 4444 5555",
                            SecondLastName = "Castillo"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1993, 2, 14),
                            Country = "Mexico",
                            Email = "andres.lopezcastro@example.com",
                            LastName = "Lopez",
                            Name = "Andres",
                            PasswordHash = "$2a$11$E/gtpZWR9eneepZ2N.RZ8uU1pPdEgDIThwWu0z1SWphA/l8wKZ37W",
                            PhoneNumber = "+52 55 6666 7777",
                            SecondLastName = "Castro"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1991, 6, 25),
                            Country = "Mexico",
                            Email = "valentina.castroperez@example.com",
                            LastName = "Castro",
                            Name = "Valentina",
                            PasswordHash = "$2a$11$sgJgQuhxosD6dVq14fEhZu/OLzqVMegCLah5QTNXclfArIMik57N6",
                            PhoneNumber = "+52 33 1111 2222",
                            SecondLastName = "Perez"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1986, 12, 7),
                            Country = "Mexico",
                            Email = "pedro.jimenezmorales@example.com",
                            LastName = "Jimenez",
                            Name = "Pedro",
                            PasswordHash = "$2a$11$al8ubhvQgGtzuamz0bJyx.SrcAlFEsP1KnW375rBVxrVOjUAHSp1m",
                            PhoneNumber = "+52 81 9999 0000",
                            SecondLastName = "Morales"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1994, 4, 12),
                            Country = "Mexico",
                            Email = "mariana.diazherrera@example.com",
                            LastName = "Diaz",
                            Name = "Mariana",
                            PasswordHash = "$2a$11$AHiQFYH2gxYShoYGvYiN9uQK6a4GkqyhOcepavzukcfjPl6wADyKy",
                            PhoneNumber = "+52 55 3333 4444",
                            SecondLastName = "Herrera"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1989, 10, 20),
                            Country = "Mexico",
                            Email = "javier.moralesjimenez@example.com",
                            LastName = "Morales",
                            Name = "Javier",
                            PasswordHash = "$2a$11$Otrdi7.pTg7pkZpUcT/LzuBaLW4c7hvY2G.FMIxLUZc1ndUis1kd6",
                            PhoneNumber = "+52 33 5555 6666",
                            SecondLastName = "Jimenez"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1996, 1, 8),
                            Country = "Mexico",
                            Email = "gabriela.fernandeztorres@example.com",
                            LastName = "Fernandez",
                            Name = "Gabriela",
                            PasswordHash = "$2a$11$KHdLV.FJyGMXmhZvBOf7lO7TO784Cmh7ODPytDhNnIVAonKPUcJv6",
                            PhoneNumber = "+52 81 2222 3333",
                            SecondLastName = "Torres"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1984, 8, 16),
                            Country = "Mexico",
                            Email = "tomas.herreramendoza@example.com",
                            LastName = "Herrera",
                            Name = "Tomas",
                            PasswordHash = "$2a$11$I9yloXUGwiZOi4Xe0yDHju4YJOm.BvcphZWJC/.h4oT/HEKWDFVce",
                            PhoneNumber = "+52 55 7777 8888",
                            SecondLastName = "Mendoza"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1997, 5, 3),
                            Country = "Mexico",
                            Email = "natalia.mendozarodriguez@example.com",
                            LastName = "Mendoza",
                            Name = "Natalia",
                            PasswordHash = "$2a$11$NlZ6RHRci9N8yoYT936E7.OlTBLioWKDtCYiwePRJlrbkNpwAVeEi",
                            PhoneNumber = "+52 33 4444 5555",
                            SecondLastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1983, 11, 22),
                            Country = "Mexico",
                            Email = "luis.ruizsanchez@example.com",
                            LastName = "Ruiz",
                            Name = "Luis Fernando",
                            PasswordHash = "$2a$11$MWsIH7/ty2YQOCoh888lU.dAU2M63arO2QaZfRr3/jz1dy/.xSmSW",
                            PhoneNumber = "+52 81 6666 7777",
                            SecondLastName = "Sanchez"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(1990, 7, 7),
                            Country = "Mexico",
                            Email = "elena.gonzalezreyes@example.com",
                            LastName = "Gonzalez",
                            Name = "Elena",
                            PasswordHash = "$2a$11$9KmQ6Y757O9PVllhIf3S4Ooyz9FXBAfu.v4VyLRrWx7FapuBkiRWS",
                            PhoneNumber = "+52 55 8888 9999",
                            SecondLastName = "Reyes"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(1986, 3, 19),
                            Country = "Mexico",
                            Email = "ricardo.reyesgarcia@example.com",
                            LastName = "Reyes",
                            Name = "Ricardo",
                            PasswordHash = "$2a$11$U37HY6gUSSOtLo.wiD1hVe98xTmE/4jCLF2ZEptZ9Wm44VuIfpLBi",
                            PhoneNumber = "+52 33 0000 1111",
                            SecondLastName = "Garcia"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(1993, 9, 14),
                            Country = "Mexico",
                            Email = "isabel.garciamoreno@example.com",
                            LastName = "Garcia",
                            Name = "Isabel",
                            PasswordHash = "$2a$11$dveQzUq9WgmHdAwI15dNPOicJe1F4Neu0NQM3Vj90rk7M4TEs0Xxu",
                            PhoneNumber = "+52 81 3333 4444",
                            SecondLastName = "Moreno"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(1988, 6, 30),
                            Country = "Mexico",
                            Email = "daniel.morenosilva@example.com",
                            LastName = "Moreno",
                            Name = "Daniel",
                            PasswordHash = "$2a$11$DBD877hoVbdmSQYZspVeTu4Yb.5Vj/i6jUDaCLGpinu2j6dPeFQAu",
                            PhoneNumber = "+52 55 5555 6666",
                            SecondLastName = "Silva"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(1995, 12, 5),
                            Country = "Mexico",
                            Email = "carmen.silvanavarro@example.com",
                            LastName = "Silva",
                            Name = "Carmen",
                            PasswordHash = "$2a$11$n11/iNpDNxjun4mZ/bSw.uvEZ4PmDF/o4OSG5DgdlGGEJVJDBKNc2",
                            PhoneNumber = "+52 33 2222 3333",
                            SecondLastName = "Navarro"
                        });
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Exchange", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.Product", "InitiatorProduct")
                        .WithMany()
                        .HasForeignKey("InitiatorProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("monchotradebackend.models.entities.User", "InitiatorUser")
                        .WithMany("InitiatedExchanges")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("monchotradebackend.models.entities.Product", "ReceiverProduct")
                        .WithMany()
                        .HasForeignKey("ReceiverProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("monchotradebackend.models.entities.User", "ReceiverUser")
                        .WithMany("ReceivedExchanges")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatorProduct");

                    b.Navigation("InitiatorUser");

                    b.Navigation("ReceiverProduct");

                    b.Navigation("ReceiverUser");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.Category", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("monchotradebackend.models.entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProductImage", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.ProfileImage", b =>
                {
                    b.HasOne("monchotradebackend.models.entities.User", "User")
                        .WithOne("ProfileImage")
                        .HasForeignKey("monchotradebackend.models.entities.ProfileImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("monchotradebackend.models.entities.User", b =>
                {
                    b.Navigation("InitiatedExchanges");

                    b.Navigation("Products");

                    b.Navigation("ProfileImage");

                    b.Navigation("ReceivedExchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
